version: '2'
services:
  ingress-mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: ingress-mysql-01
    environment:
      - MYSQL_ROOT_PASSWORD=ingress-is-great
    volumes:
      - /home/zhicheng.qi/mysql/data:/var/lib/mysql
  ingress-web:
    build: .
    container_name: ingress-web-01
    ports:
      - "9002:80"
    depends_on:
      - ingress-mysql
    links:
      - ingress-mysql
