version: '2'
services:
  ingress-mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: ingress-mysql-01
    environment:
      - MYSQL_ROOT_PASSWORD=ingress-is-great
      - MYSQL_DATABASE=ingress_spider
    volumes:
      - ~/mysql/data:/var/lib/mysql
  ingress-web:
    build: .
    container_name: ingress-web-01
    ports:
      - "9002:80"
    depends_on:
      - ingress-mysql
      - ingress-rabbit
    links:
      - ingress-mysql
      - ingress-rabbit:rabbit
  ingress-rabbit:
    image: rabbitmq:3
    container_name: ingress-rabbit-01
  ingress-phantomjs-worker:
    build: ingress-google-auth
    container_name: ingress-phantomjs-worker-01
    depends_on:
      - ingress-rabbit
    links:
      - ingress-rabbit:rabbit
